version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3

  web1:
    build: .
    environment:
      - FLASK_ENV=production
    ports:
      - "5101:5100"
    depends_on:
      - rabbit

  web2:
    build: .
    environment:
      - FLASK_ENV=production
    ports:
      - "5102:5100"
    depends_on:
      - rabbit

  web3:
    build: .
    environment:
      - FLASK_ENV=production
    ports:
      - "5103:5100"
    depends_on:
      - rabbit

  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  worker_1:
    build: .
    hostname: worker_1
    volumes:
      - .:/app
    entrypoint: celery
    command: -A workerA worker --loglevel=info
    depends_on:
      - rabbit

  worker_2:
    build: .
    hostname: worker_2
    volumes:
      - .:/app
    entrypoint: celery
    command: -A workerA worker --loglevel=info
    depends_on:
      - rabbit

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: