global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web1:5100', 'web2:5100', 'web3:5100']
  
  - job_name: 'celery'
    static_configs:
      - targets: ['worker_1:5555', 'worker_2:5555']
  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbit:15672']